### ISSUE TITLE
Update instructions to run hello world

### ISSUE THREAD

**Issue by boydm** [SEL4PROJ/rumprun-sel4-demoapps#1]
Hi! I'm super interested in this project. Thank you!

The readme (and the blog) both give instructions to run the helloworld-rumprun-ia32_defconfig, which is no longer in the configs directory. What is the right way to get started?

At least the readme should be updated with new instructions (including the right path to the manifest) please...

**Comment by kent-mcleod** [comment]
Hey, thanks for drawing this to our attention.  The configs were recently renamed to follow a new naming strategy of `$(appname)-$(seL4 arch)-$(target_platform)_defconfig`.  Available configurations can be found in the configs folder.  I updated the READMEs internally and it should get pushed out sometime in the next few hours.

**Comment by boydm** [comment]
Next question... As someone coming at this from a different programming environment, where do I find the url to the manifest? The readme just says

repo init -u $(GIT URL TO MANIFEST)

without actually saying where the manifest is. Please advise.

**Comment by boydm** [comment]
Got it. The correct line appears to be

repo init -u http://github.com/SEL4PROJ/rumprun-sel4-demoapps -m default.xml
