### ISSUE TITLE
ninja build error

### ISSUE THREAD

**Issue by wjhtinger** [SEL4PROJ/rumprun-sel4-demoapps#12]
ubuntu-20.04.3
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

What's wrong?

/home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/dev/pci/files.pci:54: attaching undefined device `iop'
dependall ===> /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/fs
dependall ===> /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/fs/lib
dependall ===> /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/fs/lib/libcd9660
dependall ===> /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/kern
dependall ===> /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/kern/lib
dependall ===> /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/kern/lib/libcrypto
dependall ===> /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/fs/lib/libefs
/home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/fs/lib/libefs/../../../../fs/efs/efs_subr.c: In function 'efs_sb_checksum':
/home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/fs/lib/libefs/../../../../fs/efs/efs_subr.c:66:2: error: converting a packed 'struct efs_sb' pointer (alignment 1) to a '__uint16_t' {aka 'short unsigned int'} pointer (alignment 2) may result in an unaligned pointer value [-Werror=address-of-packed-member]
   66 |  uint16_t *sbarray = (uint16_t *)esb;
      |  ^~~~~~~~
In file included from /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/fs/lib/libefs/../../../../fs/efs/efs_subr.c:36:
/home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/fs/lib/libefs/../../../../fs/efs/efs_sb.h:37:8: note: defined here
   37 | struct efs_sb {
      |        ^~~~~~
cc1: all warnings being treated as errors
--- efs_subr.o ---
*** [efs_subr.o] Error code 1

nbmake[5]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/fs/lib/libefs
1 error

nbmake[5]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/fs/lib/libefs
--- dependall ---
*** [dependall] Error code 2

nbmake[4]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/fs/lib/libefs
1 error

nbmake[4]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/fs/lib/libefs
--- dependall-libefs ---
*** [dependall-libefs] Error code 2

nbmake[3]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/fs/lib
1 error

nbmake[3]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/fs/lib
--- dependall-lib ---
*** [dependall-lib] Error code 2

nbmake[2]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/fs
1 error

nbmake[2]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/fs
--- dependall-fs ---
*** [dependall-fs] Error code 2

nbmake[1]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump
A failure has been detected in another branch of the parallel make

nbmake[5]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/kern/lib/libcrypto
--- dependall ---
*** [dependall] Error code 2

nbmake[4]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/kern/lib/libcrypto
1 error

nbmake[4]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/kern/lib/libcrypto
--- dependall-libcrypto ---
*** [dependall-libcrypto] Error code 2

nbmake[3]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/kern/lib
1 error

nbmake[3]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/kern/lib
--- dependall-lib ---
*** [dependall-lib] Error code 2

nbmake[2]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/kern
1 error

nbmake[2]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/kern
--- dependall-kern ---
*** [dependall-kern] Error code 2

nbmake[1]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump
A failure has been detected in another branch of the parallel make

nbmake[4]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/librump/rumpkern
--- dependall ---
*** [dependall] Error code 2

nbmake[3]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/librump/rumpkern
1 error

nbmake[3]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/librump/rumpkern
--- dependall-rumpkern ---
*** [dependall-rumpkern] Error code 2

nbmake[2]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/librump
1 error

nbmake[2]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/librump
--- dependall-librump ---
*** [dependall-librump] Error code 2

nbmake[1]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump
3 errors

nbmake[1]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump
--- dependall-/home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump ---
*** [dependall-/home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump] Error code 2

nbmake: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd
1 error

nbmake: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd
>> ERROR:
>> make /home/wangjh/work/sel4/rumprun/build-hello2/projects/rumprun/x86_64/sel4-obj/buildrump.sh/Makefile.all dependall
ninja: build stopped: subcommand failed.

**Comment by kent-mcleod** [comment]
The issue that there's old src-netbsd code that compiles with -Werror and newer compilers introduce new warning types that cause errors in code that compiled fine with older compilers.

These warnings should have been suppressed in this change: https://github.com/seL4/rumprun/commit/04464ab931c28ca1c78e807741d82a4792660183

You could try also adding `-Wno-address-of-packed-member` to that list of excludes and see if it helps.

**Comment by wjhtinger** [comment]
> The issue that there's old src-netbsd code that compiles with -Werror and newer compilers introduce new warning types that cause errors in code that compiled fine with older compilers.
> 
> These warnings should have been suppressed in this change: [seL4/rumprun@04464ab](https://github.com/seL4/rumprun/commit/04464ab931c28ca1c78e807741d82a4792660183)
> 
> You could try also adding `-Wno-address-of-packed-member` to that list of excludes and see if it helps.

I have add `-Wno-address-of-packed-member` to the list as below:
# Ignore errors that cause compile to fail for GCC 8
if(NOT "${CMAKE_C_COMPILER_VERSION}" VERSION_LESS 8.0)
    list(
        APPEND
            RUMPKERNEL_FLAGS
            -F
            CFLAGS='-Wno-cast-function-type
            -Wno-packed-not-aligned
            -Wno-tautological-compare
	    -Wno-address-of-packed-member'
    )
endif()

But there are other errors still. So, if I can remove the -Werror totally somewhere?

In file included from /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/net/lib/libnet/../../../../sys/systm.h:427,
                 from /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/net/lib/libnet/../../../../sys/timevar.h:66,
                 from /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/net/lib/libnet/../../../../sys/time.h:296,
                 from /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/net/lib/libnet/../../../../sys/param.h:145,
                 from /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/net/lib/libnet/../../../../net/if.c:105:
In function 'ifreq_setaddr',
    inlined from 'ifreq_setaddr' at /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/net/lib/libnet/../../../../net/if.c:2837:1,
    inlined from 'if_mcast_op' at /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/net/lib/libnet/../../../../net/if.c:3050:3:
/home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/net/lib/libnet/../../../../lib/libkern/libkern.h:374:26: error: '__builtin_memset' offset [33, 144] from the object at 'ifr' is out of the bounds of referenced subobject 'ifru_addr' with type 'struct sockaddr' at offset 16 [-Werror=array-bounds]
  374 | #define memset(d, v, l)  __builtin_memset(d, v, l)
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/net/lib/libnet/../../../../net/if.c:2857:2: note: in expansion of macro 'memset'
 2857 |  memset(&ifr->ifr_addr, 0, len);
      |  ^~~~~~
cc1: all warnings being treated as errors
--- if.o ---
*** [if.o] Error code 1

nbmake[5]: stopped in /home/wangjh/work/sel4/rumprun/projects/rumprun/src-netbsd/sys/rump/net/lib/libnet
1 error

**Comment by wjhtinger** [comment]
ninja build success now, thank you.  I add the config as below:
_-Wno-address-of-packed-member
-Wno-array-bounds
-Wno-maybe-uninitialized'_
