### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by wjhtinger** [SEL4PROJ/rumprun-sel4-demoapps#16]
No one reply questions

**Comment by lsf37** [comment]
Sadly the rumprun-seL4 project is not very alive at the moment. It's not dead yet, CI is still running and passing, but we don't have an active maintainer for it at the moment. So I guess not dead, but on artificial life support..

If someone would be interested and would volunteer that would be great, I think the content is pretty cool.

**Comment by MaxCoetzee** [comment]
Hi, I'm interested in testing out rumprun-seL4 to potentially use it in a project, but I can't get any of the non-trivial demos to compile and/or run.

Am I understanding correctly that CI only checks if the `hello` app works and then proceeds to update the dependencies (including the seL4 kernel)? If that is the case, it would explain a lot of the errors I'm running into.

Thank you for your time and response in advance.

**Comment by lsf37** [comment]
Yes, CI only checks the `hello` app. There's unfortunately nobody working on this project at the moment.
